name: first_pipeline
on: push
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "Hello, Commit happened successfully"
      - name: step2
        run: echo "step2"
      - name: step3
        run: |
          echo "hello from step3"
          hostname
          pwd
          id
